# Generated by Django 6.0.3 on 2026-03-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_survey_alter_question_options_question_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
