# Generated by Django 6.0.3 on 2026-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Bitiş tarihi zorunlu değildir. Boş bırakırsanız anket süresiz olur.', null=True, verbose_name='end date'),
        ),
    ]
